/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;
import java.util.Random;
import java.time.LocalDateTime ;
import java.time.format.DateTimeFormatter;
import java.util.Timer;
import java.util.TimerTask;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello world!");
        int dogCount = 1;
        pluralize("dog", dogCount);

        int catCount = 2;
        pluralize("cat", catCount);

        int turtleCount = 0;
        pluralize("turtle", turtleCount);

        flipNHeads(5);

        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {                 System.out.println( clock());
            }
        }, 0, 1000);
    }


    public static void pluralize (String animal, int animalCount){
        if (animalCount == 0 || animalCount>1){
            System.out.println("I own " + animalCount + " " + animal + "s.");
        }else{
            System.out.println("I own " + animalCount + " " +  animal +".");
        }
    }

    public static void flipNHeads (int n){
        int headCount = 0;
        int whileCounter = 0;
        
        while(headCount != n){
            double randomNumber = Math.random();
            
            if (randomNumber < 0.5){
                System.out.println("tails");
                headCount = 0;
            }else{
                System.out.println("head");
                headCount ++;
            }
            whileCounter ++;
        }
        System.out.println("It took " + whileCounter + " flips to flip " + n + " heads in a row");
        
    }
    public static   String clock(){

        LocalDateTime now = LocalDateTime.now();
        int hour = now.getHour();
        int minute = now.getMinute();
        int second = now.getSecond();
        String time = hour+":"+minute+":"+second;
        // DateTimeFormatter format = DateTimeFormatter.ofPattern("HH:mm:ss");
        // String formatDateTime = now.format(format);

        return time;
    }


}
