/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRestaurantClass() {
        Restaurant restaurant = new Restaurant("Elul", 5.0,"$");
        System.out.println(restaurant.toString());
        assertEquals("Restaurant Name: Elul\nVotes: 5.0\nCurrency: $" ,restaurant.toString());
    }

    @Test public void testReviewClass() {
        String restName = "Elul";
        double restVotes = 5.0;
        String restCurrency = "$";
        Restaurant restaurant = new Restaurant(restName,restVotes, restCurrency);
        Review classUnderTest = new Review("Aseel Albanna", 5.0, "Wow!", restName, restVotes);

        assertEquals("Name: Aseel Albanna\nMessage: I voted for Elul restaurant, and give it 5.0, So it has now 5.0 stars. Wow!",
                classUnderTest.toString());
    }

    @Test public void testAddReviewMethod(){
        String restName = "Elul";
        double restVotes = 5.0;
        String restCurrency = "$";
        Restaurant restaurant = new Restaurant(restName,restVotes, restCurrency);
        Review classUnderTest = new Review("Aseel Albanna", 5.0, "Wow!", restName, restVotes);

    }

    @Test public void ReviewTestToString () {

        Review review = new Review("Aseel Albanna", 5.0, "Great Restaurant", "Elul", 5.0);
        assertEquals("Name: " + review.getAuthor() +
                "\nMessage: I voted for "+ review.getRestaurantName() + " restaurant, and give it " + review.getVotesGiven() + ", So it has now "+ review.getVotes() + " stars. Wow!" ,review.toString());
    }

    @Test public void testAddReview(){
        Review review = new Review("Aseel Albanna", 5.0, "Great Restaurant!", "Elul", 5.0);
        Restaurant restaurant = new Restaurant("Elul", 5.0,"$");
        restaurant.addReview(review);
        System.out.println(review.toString());
        assertEquals("Name: Aseel Albanna\nMessage: I voted for Elul restaurant, and give it 5.0, So it has now 10.0 stars. Wow!",review.toString());
    }


}
